version: '3.9'

name: 'elk-stack'

services:
  mariadb:
    container_name: 'elk-mariadb'
    image: mariadb:10
    restart: unless-stopped
    ports:
      - 33065:3306
    volumes:
      - .volumes/conf.d:/etc/mysql/conf.d:ro
      - .volumes/initdb:/docker-entrypoint-initdb.d
      - .volumes/logs:/var/log/mysql
      - .volumes/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: root@password
    networks:
      - elk-mariadb

  filebeat:
    depends_on:
      - mariadb
    container_name: 'elk-mariadb-filebeat'
    build:
      context: .
      dockerfile: filebeat/Dockerfile
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - .volumes/logs:/var/log/mysql
    user: root
    command:
      - -e
      - --strict.perms=false
    network_mode: host

networks:
  elk-mariadb:
    driver: bridge
