- pipeline.id: main
  path.config: /usr/share/logstash/pipeline/logstash.conf

- pipeline.id: application
  path.config: /usr/share/logstash/pipeline/application.conf

- pipeline.id: slow-query
  path.config: /usr/share/logstash/pipeline/slow-query.conf
