- pipeline.id: main
  path.config: /usr/share/logstash/pipeline/logstash.conf

- pipeline.id: myinput
  path.config: /usr/share/logstash/pipeline/myinput.conf

- pipeline.id: nestjs
  path.config: /usr/share/logstash/pipeline/nestjs.conf
